  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (155,257,"Deirdre","sociis natoque penatibus et",837);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (816,111,"Jasmine","id risus quis diam luctus lobortis.",713);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (722,377,"Zephr","Morbi neque tellus, imperdiet non, vestibulum nec,",841);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (643,39,"Bernard","Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam",857);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (429,178,"Jamal","leo, in lobortis",500);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (454,259,"Hall","vel turpis. Aliquam adipiscing lobortis risus. In mi pede,",665);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (763,342,"Peter","ipsum cursus vestibulum. Mauris magna. Duis",162);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (750,797,"Skyler","Lorem ipsum dolor sit amet, consectetuer",876);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (523,760,"Mari","malesuada vel, venenatis vel,",795);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (714,357,"Brent","neque.",35);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (855,702,"Rogan","fermentum",488);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (443,582,"Xavier","nibh dolor, nonummy",87);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (643,632,"Harper","mauris. Morbi non sapien molestie orci",655);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (174,456,"Rhea","elit erat vitae risus.",949);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (589,909,"Katell","Phasellus libero mauris, aliquam eu,",107);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (834,982,"Juliet","eleifend nec, malesuada ut, sem. Nulla interdum.",213);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (159,948,"Tad","ipsum. Suspendisse",838);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (816,658,"Mona","enim. Mauris quis turpis vitae",620);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (959,936,"Ima","Proin vel nisl. Quisque fringilla euismod enim.",762);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (124,731,"Sean","convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc",667);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (245,958,"Keely","justo. Proin non massa",918);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (797,82,"Sylvester","dapibus id, blandit at, nisi. Cum sociis natoque",207);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (132,948,"Emi","amet,",621);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (824,902,"Wyoming","sociosqu ad litora torquent per",111);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (822,880,"Kadeem","Lorem ipsum dolor sit amet,",496);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (5,344,"Rigel","Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas",992);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (510,676,"Dacey","eu lacus. Quisque imperdiet, erat nonummy ultricies",776);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (393,28,"Shaine","mattis velit justo nec ante. Maecenas mi",366);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (89,592,"Colin","ligula elit, pretium et, rutrum non, hendrerit id,",357);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (947,293,"Elaine","tortor. Nunc",614);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (504,814,"Carlos","Vestibulum",604);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (420,180,"Irma","Proin",446);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (299,72,"Mary","imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,",263);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (224,291,"Yoshio","elit. Aliquam auctor, velit eget laoreet posuere,",685);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (364,407,"Hayes","magna a tortor. Nunc commodo",932);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (307,545,"Alvin","elit, dictum eu, eleifend nec, malesuada",196);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (123,201,"Cora","nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum",341);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (479,994,"Kirby","lobortis",44);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (95,966,"Allen","vehicula aliquet libero. Integer in",3);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (835,71,"Constance","vitae, erat.",804);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (412,906,"Richard","consequat, lectus sit",152);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (238,426,"Emmanuel","non, feugiat nec, diam. Duis mi enim, condimentum eget,",578);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (23,623,"Charissa","luctus, ipsum leo elementum sem, vitae aliquam",24);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (581,82,"Hamish","aptent taciti sociosqu ad litora torquent",261);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (740,381,"Dustin","at pretium aliquet, metus urna convallis erat, eget tincidunt dui",594);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (460,848,"Kermit","lectus. Cum sociis natoque",243);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (983,340,"Fulton","lacus. Ut nec urna",94);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (668,711,"Darrel","nec tempus mauris erat eget ipsum. Suspendisse sagittis.",126);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (668,923,"Naida","dignissim lacus. Aliquam rutrum lorem ac risus. Morbi",231);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (819,691,"Camden","Cras eu tellus eu augue porttitor interdum. Sed auctor odio",684);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (940,950,"August","et, rutrum non, hendrerit id, ante. Nunc mauris sapien,",476);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (797,200,"Kennan","libero. Proin mi. Aliquam gravida mauris ut mi. Duis",738);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (134,557,"Bradley","Nunc",184);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (363,869,"Beau","iaculis enim,",180);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (430,178,"Katelyn","pharetra sed, hendrerit a, arcu.",81);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (739,578,"Noelani","tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae",568);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (57,651,"Reece","eu metus. In",590);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (344,616,"Ocean","consequat, lectus sit amet luctus vulputate, nisi sem",41);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (133,697,"Eliana","nonummy",655);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (544,870,"Chancellor","sed orci lobortis augue scelerisque mollis. Phasellus libero",122);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (689,561,"Bell","luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",5);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (712,664,"Kasper","commodo auctor velit. Aliquam nisl. Nulla eu",700);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (28,651,"Kelsie","eu",15);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (494,489,"Fletcher","in, cursus et, eros.",558);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (979,106,"Stacy","sagittis placerat. Cras dictum",945);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (767,189,"Chelsea","leo. Morbi neque",503);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (301,937,"Alec","elit. Etiam laoreet, libero",398);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (692,290,"Callum","orci. Ut",321);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (103,600,"Yoko","mattis. Integer eu lacus. Quisque imperdiet, erat",37);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (881,868,"Damon","ut cursus luctus, ipsum leo elementum",200);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (102,378,"Connor","ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis",856);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (659,306,"Wanda","egestas. Fusce aliquet magna a neque.",490);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (146,882,"Hunter","Donec",730);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (711,474,"Hector","Proin dolor.",841);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (233,815,"Nichole","nulla.",683);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (225,716,"Hadley","elementum purus, accumsan interdum libero",356);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (26,566,"Matthew","nonummy ut,",576);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (530,759,"Lavinia","nec, eleifend non, dapibus rutrum, justo. Praesent",537);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (782,313,"Ingrid","ut, pharetra",786);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (432,388,"Caleb","Praesent",699);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (682,88,"Demetria","morbi tristique",992);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (201,273,"Castor","posuere, enim",797);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (458,103,"Sebastian","sodales. Mauris blandit enim consequat",821);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (799,592,"Karyn","Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis,",70);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (227,7,"Justina","nisl elementum purus, accumsan interdum libero dui",302);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (847,422,"Melvin","tellus.",785);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (437,67,"Nasim","pharetra sed, hendrerit a, arcu. Sed et",78);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (72,569,"Elton","Mauris",986);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (88,18,"Gannon","magnis dis",438);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (150,205,"Bevis","amet",256);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (525,51,"Denton","vitae, orci. Phasellus dapibus quam",266);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (510,931,"Reese","accumsan",976);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (707,523,"Herman","ac nulla. In tincidunt congue turpis. In condimentum.",131);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (498,438,"Amelia","malesuada malesuada. Integer id magna et ipsum cursus vestibulum.",501);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (285,348,"Kamal","ornare, facilisis eget, ipsum.",498);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (532,461,"Prescott","varius et,",482);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (8,713,"Kitra","facilisis eget, ipsum. Donec sollicitudin adipiscing ligula.",7);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (751,112,"Calista","erat volutpat. Nulla",478);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (705,635,"Guy","commodo ipsum. Suspendisse non leo.",578);
  INSERT INTO food (fid,rid,foodname,description,cost) VALUES (979,696,"Dane","Aliquam erat volutpat. Nulla dignissim.",307);
